export const kk = {
  start: 'Ойынды бастау', continue: 'Жалғастыру', achievements: 'Жетістіктер', profile: 'Профиль',
  map: 'Карта', home: 'Басты бет', back: 'Артқа', level: 'Деңгей', rank: 'Дәреже', progress: 'Жалпы прогресс',
  menu: 'Мәзір', closeMenu: 'Мәзірді жабу', settings: 'Баптаулар', moveUp: 'Жоғары жылжыту', moveDown: 'Төмен жылжыту', dragItem: 'Сүйреп жылжыту',
  stars: 'Жұлдыздар', sciencePoints: 'Ғылым ұпайлары', streak: 'Жауаптар сериясы', completed: 'аяқталды', locked: 'Жабық', current: 'Ағымдағы',
  know: 'БІЛУ', understand: 'ТҮСІНУ', apply: 'ҚОЛДАНУ ЖӘНЕ ТАЛДАУ', challenge: 'ҒЫЛЫМИ СЫНАҚ',
  check: 'Нәтижені тексеру', retry: 'Қайта орындау', next: 'Келесі тапсырма', finish: 'Деңгейді аяқтау', why: 'Неліктен?',
  theory: 'Зерттеуші жазбасы', instruction: 'Тапсырма', hint: 'Көмек', result: 'Нәтиже', observation: 'Бақылау',
  correct: 'Дұрыс! Ғылыми дәлел қабылданды.', wrong: 'Әзірге сәйкес емес. Дәлелді қайта тексер.',
  dragHelp: 'Карточканы сүйреп апар немесе карточка мен санатты кезекпен бас.',
  selectPair: 'Терминді, содан кейін сәйкес анықтаманы таңда.',
  sequenceHelp: 'Кезеңдерді сүйреп немесе ↑ ↓ батырмаларымен ретте.',
  labHelp: 'Параметрді өзгерт, үлгіні бақыла және деректер бойынша қорытынды жаса.',
  boss: 'ҒЫЛЫМИ МИССИЯ', bossLocked: 'Алдымен осы аймақтың барлық Challenge деңгейін аяқта.',
  bossStage: 'Миссия кезеңі', missionComplete: 'Миссия орындалды! Келесі аймақ ашылды.',
  enterName: 'Зерттеушінің аты', save: 'Сақтау', reset: 'Прогресті өшіру', resetConfirm: 'Барлық прогресті өшіруге сенімдісің бе?',
  soundOn: 'Дыбысты өшіру', soundOff: 'Дыбысты қосу', unlocked: 'Жаңа жетістік!', noAchievements: 'Алғашқы жетістік алда.',
  sourceNote: 'Ғылыми мазмұн қазақ және орыс конспектілерінен алынған.', allZones: 'Ғылыми аумақтар',
  leaderboard: 'Рейтинг', studentsLeaderboard: 'Оқушылар рейтингі', overall: 'Жалпы', thisWeek: 'Осы апта', thisMonth: 'Осы ай', bySection: 'Бөлімдер', myClass: 'Менің сыныбым',
  myPlace: 'Сіздің орныңыз', nextPlace: 'Келесі орынға дейін', fullLeaderboard: 'Толық рейтинг', weeklyLeaders: 'Апта көшбасшылары', nearbyRivals: 'Жақын қарсыластар', position: 'орын',
  onlineProfile: 'Онлайн профиль', nickname: 'Лақап аты', displayName: 'Аты', grade: 'Сынып', schoolOptional: 'Мектеп (міндетті емес)', avatar: 'Аватар', showGrade: 'Рейтингте сыныпты көрсету',
  createProfile: 'Профиль жасау', updateProfile: 'Профильді жаңарту', profileSaved: 'Профиль сақталды', nicknameTaken: 'Бұл лақап ат қолданылып жатыр. Басқа лақап ат таңдаңыз.', nicknameInvalid: 'Лақап ат 3–20 таңбадан тұрып, тек әріп, сан, _ немесе - қамтуы керек.',
  leaderboardUnavailable: 'Интернет байланысын тексеріңіз.', leaderboardNotConfigured: 'Онлайн рейтинг әзірге қосылмаған.', backendUnavailable: 'Рейтингті жүктеу мүмкін болмады. Кейінірек қайталап көріңіз.', retryConnection: 'Қайта қосылу',
  nextPage: 'Келесі 50', previousPage: 'Алдыңғы 50', noResults: 'Бұл сүзгі бойынша нәтиже жоқ.', onlineXp: 'Онлайн XP', challengePoints: 'Challenge ұпайлары', completedLevels: 'Аяқталған деңгейлер', leaderboardPrivacy: 'Рейтингте тек лақап ат, аватар және ойын нәтижелері көрсетіледі.',
  perfectBonus: '3 жұлдыз үшін бір реттік +20 XP бонусы', repeatNoXp: 'Бұл деңгейдің негізгі XP ұпайы бұрын алынған.', rankUp: 'Сіз рейтингте {count} орынға көтерілдіңіз!', refresh: 'Жаңарту',
  scoringSystem: 'Ұпайлар қалай есептеледі?',
}
