export const ru = {
  start: 'Начать игру', continue: 'Продолжить', achievements: 'Достижения', profile: 'Профиль',
  map: 'Карта', home: 'Главная', back: 'Назад', level: 'Уровень', rank: 'Ранг', progress: 'Общий прогресс',
  menu: 'Меню', closeMenu: 'Закрыть меню', settings: 'Настройки', moveUp: 'Переместить выше', moveDown: 'Переместить ниже', dragItem: 'Перетащить',
  stars: 'Звёзды', sciencePoints: 'Science Points', streak: 'Серия', completed: 'завершено', locked: 'Закрыто', current: 'Текущий',
  know: 'ЗНАТЬ', understand: 'ПОНИМАТЬ', apply: 'ПРИМЕНЯТЬ И АНАЛИЗИРОВАТЬ', challenge: 'SCIENCE CHALLENGE',
  check: 'Проверить', retry: 'Попробовать снова', next: 'Далее', finish: 'Завершить уровень', why: 'Почему?',
  theory: 'Запись исследователя', instruction: 'Задание', hint: 'Подсказка', result: 'Результат', observation: 'Наблюдение',
  correct: 'Верно! Научное доказательство принято.', wrong: 'Пока не сходится. Перепроверь доказательства.',
  dragHelp: 'Перетащи карточку или по очереди нажми карточку и категорию.',
  selectPair: 'Выбери термин, затем подходящее определение.',
  sequenceHelp: 'Перетащи этапы или используй кнопки ↑ ↓.',
  labHelp: 'Меняй параметр, наблюдай модель и сделай вывод по данным.',
  boss: 'SCIENCE MISSION', bossLocked: 'Сначала заверши все Challenge этой территории.',
  bossStage: 'Этап миссии', missionComplete: 'Миссия выполнена! Следующая территория открыта.',
  enterName: 'Имя исследователя', save: 'Сохранить', reset: 'Сбросить прогресс', resetConfirm: 'Точно удалить весь прогресс?',
  soundOn: 'Выключить звук', soundOff: 'Включить звук', unlocked: 'Новое достижение!', noAchievements: 'Первое достижение ещё впереди.',
  sourceNote: 'Научное содержание основано на казахском и русском конспектах.', allZones: 'Научные территории',
  leaderboard: 'Рейтинг', studentsLeaderboard: 'Рейтинг учеников', overall: 'Общий', thisWeek: 'Эта неделя', thisMonth: 'Этот месяц', bySection: 'Разделы', myClass: 'Мой класс',
  myPlace: 'Ваше место', nextPlace: 'До следующего места', fullLeaderboard: 'Весь рейтинг', weeklyLeaders: 'Лидеры недели', nearbyRivals: 'Ближайшие соперники', position: 'место',
  onlineProfile: 'Онлайн-профиль', nickname: 'Никнейм', displayName: 'Имя', grade: 'Класс', schoolOptional: 'Школа (необязательно)', avatar: 'Аватар', showGrade: 'Показывать класс в рейтинге',
  createProfile: 'Создать профиль', updateProfile: 'Обновить профиль', profileSaved: 'Профиль сохранён', nicknameTaken: 'Этот никнейм уже используется. Выберите другой.', nicknameInvalid: 'Никнейм должен содержать 3–20 символов: буквы, цифры, _ или -.',
  leaderboardUnavailable: 'Проверьте подключение к интернету.', leaderboardNotConfigured: 'Онлайн-рейтинг пока не подключён.', backendUnavailable: 'Не удалось загрузить рейтинг. Попробуйте ещё раз позже.', retryConnection: 'Подключиться снова',
  nextPage: 'Следующие 50', previousPage: 'Предыдущие 50', noResults: 'Для этого фильтра результатов пока нет.', onlineXp: 'Онлайн XP', challengePoints: 'Challenge Points', completedLevels: 'Пройдено уровней', leaderboardPrivacy: 'В рейтинге видны только никнейм, аватар и игровые результаты.',
  perfectBonus: 'Разовый бонус +20 XP за 3 звезды', repeatNoXp: 'Основной XP этого уровня уже получен.', rankUp: 'Вы поднялись на {count} места!', refresh: 'Обновить',
  scoringSystem: 'Как начисляются очки?',
}
