import { useEffect, useMemo, useState } from 'react'
import { adminCopy } from '../content/admin'
import { levelById } from '../content/levels'
import { sections } from '../content/sections'
import { topics } from '../content/topics'
import { fetchAdminActivity, fetchAdminStudentAchievements, fetchAdminStudentContact, fetchAdminStudentDetail, fetchAdminStudentHistory, fetchAdminStudentProgress } from '../services/adminService'
import { fetchAdminStudentAccess, fetchAdminStudentAssignments } from '../services/learningService'
import { formatPhone } from '../services/privateContactService'
import { useGame } from '../store/GameStore'
import type { AdminAchievement, AdminActivity, AdminLevelHistory, AdminSectionProgress, AdminStudentDetail } from '../types/admin'
import type { LearningAccess, StudentAssignment } from '../types/learning'
import { AdminError, AdminLoading } from './AdminDashboard'
import { AdminMonitoring } from './AdminMonitoring'
import { formatAdminDate as formatDate } from './adminFormat'
import { AvatarImage } from '../components/AvatarImage'
import { AdminStudentContentActions } from './AdminStudentContentActions'

type DetailTab = 'overview'|'progress'|'assignments'|'topics'|'quests'|'history'|'errors'|'achievements'|'activity'

export function AdminStudentLearningDetail({ userId, onBack, onManageContent }: { userId: string; onBack: () => void; onManageContent?: (userIds: string[]) => void }) {
  const { progress: game } = useGame(); const copy = adminCopy(game.language); const kk = game.language === 'kk'
  const [detail, setDetail] = useState<AdminStudentDetail | null>(null); const [sectionProgress, setSectionProgress] = useState<AdminSectionProgress[]>([]); const [history, setHistory] = useState<AdminLevelHistory[]>([]); const [assignments, setAssignments] = useState<StudentAssignment[]>([]); const [access, setAccess] = useState<LearningAccess[]>([]); const [activity, setActivity] = useState<AdminActivity[]>([])
  const [studentAchievements,setStudentAchievements]=useState<AdminAchievement[]>([])
  const [error, setError] = useState(false); const [loading, setLoading] = useState(true); const [phone, setPhone] = useState<string | null>(null); const [tab, setTab] = useState<DetailTab>('overview')
  const load = () => { setLoading(true); setError(false); void Promise.all([fetchAdminStudentDetail(userId),fetchAdminStudentProgress(userId),fetchAdminStudentHistory(userId),fetchAdminStudentContact(userId),fetchAdminStudentAssignments(userId),fetchAdminStudentAccess(userId),fetchAdminActivity({ days: 30, eventType: null, grade: null, page: 0, userId }),fetchAdminStudentAchievements(userId)]).then(([d,p,h,c,a,x,e,achievements]) => { setDetail(d); setSectionProgress(p); setHistory(h); setPhone(c); setAssignments(a); setAccess(x); setActivity(e);setStudentAchievements(achievements) }).catch(() => setError(true)).finally(() => setLoading(false)) }
  useEffect(load, [userId])
  const topicStats = useMemo(() => topics.map((topic) => { const rows = history.filter((row) => row.levelId.startsWith(`${topic.id}-`)); const completed = new Set(rows.map((row) => row.levelId)).size; const topicAccess = access.find((item) => item.contentType === 'topic' && item.contentId === topic.id); return { topic, percent: completed / 4 * 100, attempts: rows.length, best: Math.max(0, ...rows.map((row) => row.accuracy)), stars: rows.reduce((sum, row) => sum + row.stars, 0), state: topicAccess?.accessState ?? 'locked', last: rows[0]?.completedAt ?? null } }), [history, access])
  if (loading) return <AdminLoading />; if (error || !detail) return <AdminError onRetry={load} />
  const weak = history.filter((row) => row.accuracy < 70).slice(0, 8); const latest = activity[0]; const latestLevelId = latest?.levelId ?? null; const latestLevel = latestLevelId ? levelById[latestLevelId] : null
  const tabs: Array<[DetailTab,string]> = [['overview',kk?'Шолу':'Обзор'],['progress',kk?'Прогресс':'Прогресс'],['assignments',kk?'Тапсырмалар':'Назначения'],['topics',kk?'Тақырыптар':'Темы'],['quests',kk?'Квесттер':'Квесты'],['history',kk?'Ойын тарихы':'История игры'],['errors',kk?'Қателер':'Ошибки'],['achievements',kk?'Жетістіктер':'Достижения'],['activity',kk?'Белсенділік':'Активность']]
  return <><button className="back-link" onClick={onBack}>← {copy.back}</button><header className="admin-student-hero"><AvatarImage value={detail.avatar} label={detail.nickname} /><div><small>#{detail.rank}</small><h1>{detail.nickname}</h1><p>{detail.grade ?? '—'} · {detail.school || '—'}</p><i className={detail.lastActive && Date.now()-new Date(detail.lastActive).getTime()<24*60*60_000?'status-green':'status-yellow'} /></div><div className="admin-student-kpis"><b>{detail.xp}<small>XP</small></b><b>{detail.stars}<small>⭐</small></b><b>{detail.averageAccuracy}%<small>{copy.accuracy}</small></b><b>{detail.currentStreak}<small>🔥</small></b></div></header><section className="admin-private-contact"><span>🔐</span><div><small>{copy.privateContact}</small><strong>{copy.phone}: {phone ? formatPhone(phone) : '—'}</strong></div></section><nav className="admin-detail-tabs">{tabs.map(([id,label]) => <button key={id} className={tab===id?'active':''} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {tab === 'overview' && <div className="student-overview-grid"><section className="admin-analytics-kpis"><article><small>{kk?'Жалпы прогресс':'Общий прогресс'}</small><strong>{Math.round(detail.completedLevels/detail.totalLevels*100)}%</strong></article><article><small>{copy.levels}</small><strong>{detail.completedLevels}/{detail.totalLevels}</strong></article><article><small>Challenge</small><strong>{history.filter((row)=>row.levelId.endsWith('-challenge')||row.levelId.startsWith('boss:')).length}</strong></article><article><small>{copy.lastActive}</small><strong>{formatDate(detail.lastActive,game.language)}</strong></article></section><section className="admin-last-path"><h2>{kk?'Соңғы оқу жолы':'Последний учебный маршрут'}</h2><p><b>{kk?'Бөлім':'Раздел'}:</b> {latestLevel ? sections.find((section)=>section.id===latestLevel.sectionId)?.title[game.language] ?? '—':'—'}</p><p><b>{kk?'Тақырып':'Тема'}:</b> {latestLevel ? topics.find((topic)=>topic.id===latestLevel.topicId)?.title[game.language] ?? '—':'—'}</p><p><b>{kk?'Квест':'Квест'}:</b> {latestLevelId ? levelTitle(latestLevelId,game.language):'—'}</p><p><b>{kk?'Соңғы нәтиже':'Последний результат'}:</b> {history[0] ? `${history[0].accuracy}% · ${'⭐'.repeat(history[0].stars)}`:'—'}</p></section></div>}
    {tab === 'progress' && <section className="admin-progress-panel"><h2>{copy.progress}</h2>{sectionProgress.map((row) => { const section = sections.find((item) => item.id === row.sectionId); return <article key={row.sectionId}><div><strong>{section?.title[game.language] ?? row.sectionId}</strong><span>{row.completedLevels}/{row.totalLevels} · ⭐ {row.stars} · {row.averageScore}%</span></div><div className="admin-progress-bar"><i style={{ width: `${row.completionPercent}%` }} /></div><b>{row.completionPercent}%</b></article> })}</section>}
    {tab === 'assignments' && <section className="admin-assignment-list compact"><h2>{kk?'Оқу тапсырмалары':'Учебные назначения'}</h2>{assignments.length===0?<p>{copy.noData}</p>:assignments.map((item)=><article key={item.assignmentId}><header><div><small>{item.priority.toUpperCase()}</small><h2>{item.title[game.language]}</h2></div><span>{item.status}</span></header><div className="admin-progress-bar"><i style={{width:`${item.progressPercent}%`}}/></div><footer><small>{item.progressPercent}% · {item.attempts} {kk?'әрекет':'попыток'} · {item.bestScore}%</small></footer></article>)}</section>}
    {tab === 'topics' && <section className="admin-topic-progress"><h2>{kk?'Барлық тақырыптар':'Все темы'}</h2>{topicStats.map(({topic,percent,attempts,best,stars,state,last})=><article key={topic.id}><span>{state==='completed'?'✅':state==='assigned'?'📌':state==='locked'?'🔒':state==='hidden'?'◉':'✨'}</span><div><strong>{topic.title[game.language]}</strong><small>{attempts} {kk?'әрекет':'попыток'} · {best}% · ⭐ {stars} · {last?formatDate(last,game.language):'—'}</small><div className="admin-progress-bar"><i style={{width:`${percent}%`}}/></div></div><b>{percent}%</b></article>)}</section>}
    {tab === 'quests' && <History rows={history} language={game.language} title={kk?'Квест нәтижелері':'Результаты квестов'} />}
    {tab === 'history' && <History rows={history} language={game.language} title={copy.history} />}
    {tab === 'errors' && <section className="admin-weak-card"><h2>⚠ {kk?'Қайталау қажет':'Нужно повторить'}</h2>{weak.length===0?<p>{copy.noData}</p>:weak.map((row)=><article key={`${row.levelId}-${row.attemptNumber}`}><span>{levelTitle(row.levelId,game.language)}</span><b>{row.accuracy}%</b><button type="button" onClick={() => onManageContent?.([userId])}>{kk?'Қайталауды тағайындау':'Назначить повторение'}</button></article>)}</section>}
    {tab === 'achievements' && <section className="admin-student-achievements"><header><div><small>{kk?'Ашылған жетістіктер':'Полученные достижения'}</small><h2>{studentAchievements[0]?.unlockedCount??0} / {studentAchievements[0]?.totalCount??0}</h2></div><span>🏆</span></header>{studentAchievements.length===0?<p>{copy.noData}</p>:<div>{studentAchievements.map((achievement)=><article key={achievement.code} className={`${achievement.unlocked?'unlocked':'locked'} rarity-${achievement.rarity.toLowerCase()}`}><span>{achievement.unlocked?achievement.icon:'🔒'}</span><div><strong>{achievement.title[game.language]}{achievement.selectedTitle?' · ✦':''}</strong><small>{achievement.rarity} · {achievement.current}/{achievement.target}{achievement.earnedAt?` · ${formatDate(achievement.earnedAt,game.language)}`:''}</small><div className="admin-progress-bar"><i style={{width:`${Math.min(100,achievement.current/Math.max(1,achievement.target)*100)}%`}}/></div></div></article>)}</div>}</section>}
    {tab === 'topics' && <AdminStudentContentActions userId={userId} mode="topics" access={access} language={game.language} onChanged={load} />}
    {tab === 'quests' && <AdminStudentContentActions userId={userId} mode="quests" access={access} language={game.language} onChanged={load} />}
    {tab === 'activity' && <AdminMonitoring userId={userId} />}
  </>
}

function History({ rows, language, title }: { rows: AdminLevelHistory[]; language: 'kk'|'ru'; title: string }) { const copy=adminCopy(language); return <section className="admin-history"><h2>{title}</h2>{rows.length===0?<p>{copy.noData}</p>:rows.map((row)=><article key={`${row.levelId}-${row.completedAt}-${row.attemptNumber}`}><div><strong>{levelTitle(row.levelId,language)}</strong><time>{formatDate(row.completedAt,language)}</time></div><span>{row.accuracy}%</span><span>{'⭐'.repeat(row.stars)}</span><span>{copy.attempts} {row.attemptNumber}</span><b>+{row.xpEarned} XP</b></article>)}</section> }

export const levelTitle = (id: string, language: 'kk' | 'ru') => levelById[id]?.title[language] ?? (id.startsWith('boss:') ? sections.find((section) => section.id === id.slice(5))?.bossTitle[language] : undefined) ?? id
