import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { levels } from '../content/levels'
import { sections } from '../content/sections'
import { topics } from '../content/topics'
import { createAdminAssignment, fetchAdminAssignments, updateAdminAssignment } from '../services/learningService'
import { fetchAdminStudents } from '../services/adminService'
import { useGame } from '../store/GameStore'
import type { AdminStudent } from '../types/admin'
import type { AdminAssignment, AssignmentInput, LearningContentType } from '../types/learning'
import { AdminConfirmDialog } from './AdminConfirmDialog'
import { AdminError, AdminLoading } from './AdminDashboard'
import { AvatarImage } from '../components/AvatarImage'

const nowInput = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 16)

export function AdminAssignments({ initialStudentIds = [] }: { initialStudentIds?: string[] }) {
  const { progress } = useGame(); const kk = progress.language === 'kk'
  const [rows, setRows] = useState<AdminAssignment[]>([]); const [students, setStudents] = useState<AdminStudent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false)
  const [formOpen, setFormOpen] = useState(initialStudentIds.length > 0); const [confirm, setConfirm] = useState<AssignmentInput | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  const [titleKk, setTitleKk] = useState(''); const [titleRu, setTitleRu] = useState(''); const [descriptionKk, setDescriptionKk] = useState(''); const [descriptionRu, setDescriptionRu] = useState('')
  const [targetType, setTargetType] = useState<'user'|'grade'|'all'>(initialStudentIds.length ? 'user' : 'grade'); const [targets, setTargets] = useState<string[]>(initialStudentIds); const [contentType, setContentType] = useState<LearningContentType>('topic'); const [contentIds, setContentIds] = useState<string[]>([]); const [availableFrom, setAvailableFrom] = useState(nowInput); const [dueAt, setDueAt] = useState(''); const [priority, setPriority] = useState<'normal'|'priority'>('normal')
  const load = () => { setLoading(true); setError(false); void Promise.all([fetchAdminAssignments(), fetchAdminStudents({ search: '', grade: null, active: 'all', sort: 'nickname', page: 0 })]).then(([a, s]) => { setRows(a); setStudents(s) }).catch(() => setError(true)).finally(() => setLoading(false)) }
  useEffect(load, [])
  const catalog = useMemo(() => contentType === 'section' ? sections.map((item) => ({ id: item.id, title: item.title[progress.language] })) : contentType === 'topic' ? topics.map((item) => ({ id: item.id, title: item.title[progress.language] })) : contentType === 'boss' ? sections.map((item) => ({ id: `boss:${item.id}`, title: item.bossTitle[progress.language] })) : levels.map((item) => ({ id: item.id, title: item.title[progress.language] })), [contentType, progress.language])
  const toggle = (id: string, values: string[], setter: (value: string[]) => void) => setter(values.includes(id) ? values.filter((item) => item !== id) : [...values, id])
  const submit = (event: FormEvent) => { event.preventDefault(); setMessage(''); const targetValues = targetType === 'all' ? ['all'] : targetType === 'grade' ? targets.filter((item) => ['5','6'].includes(item)) : targets; if (!targetValues.length || !contentIds.length) { setMessage(kk ? 'Кемінде бір алушы мен тапсырманы таңдаңыз.' : 'Выберите хотя бы одного получателя и один элемент.'); return } setConfirm({ titleKk, titleRu, descriptionKk, descriptionRu, availableFrom: new Date(availableFrom).toISOString(), dueAt: dueAt ? new Date(dueAt).toISOString() : null, priority, targetType, targetValues, items: contentIds.map((id) => ({ type: contentType, id })) }) }
  const create = async () => { if (!confirm) return; setBusy(true); try { await createAdminAssignment(confirm); setConfirm(null); setFormOpen(false); setTitleKk(''); setTitleRu(''); setContentIds([]); setTargets([]); setMessage(kk ? 'Тапсырма тағайындалды.' : 'Назначение создано.'); load() } catch { setMessage(kk ? 'Тапсырманы сақтау мүмкін болмады.' : 'Не удалось сохранить назначение.') } finally { setBusy(false) } }
  const update = async (item: AdminAssignment, changes: Partial<Pick<AdminAssignment,'status'|'priority'>>) => { setBusy(true); try { await updateAdminAssignment(item, changes); setMessage(kk ? 'Тапсырма жаңартылды.' : 'Назначение обновлено.'); load() } catch { setMessage(kk ? 'Өзгеріс сақталмады.' : 'Изменение не сохранено.') } finally { setBusy(false) } }
  if (loading && rows.length === 0) return <AdminLoading />
  if (error && rows.length === 0) return <AdminError onRetry={load} />
  return <><header className="admin-page-heading admin-heading-actions"><div><small>LEARNING MANAGEMENT</small><h1>{kk ? 'Тапсырмалар' : 'Назначения'}</h1></div><button className="primary-button" onClick={() => setFormOpen((value) => !value)}>＋ {kk ? 'Тапсырма құру' : 'Создать'}</button></header>
    {message && <p className="admin-notice" role="status">{message}</p>}
    {formOpen && <form className="admin-assignment-form" onSubmit={submit}><h2>{kk ? 'Жаңа тапсырма' : 'Новое назначение'}</h2><div className="admin-form-grid"><label>Қазақша атауы<input required maxLength={120} value={titleKk} onChange={(e) => setTitleKk(e.target.value)} /></label><label>Название на русском<input required maxLength={120} value={titleRu} onChange={(e) => setTitleRu(e.target.value)} /></label><label>Қазақша сипаттама<textarea maxLength={1000} value={descriptionKk} onChange={(e) => setDescriptionKk(e.target.value)} /></label><label>Описание на русском<textarea maxLength={1000} value={descriptionRu} onChange={(e) => setDescriptionRu(e.target.value)} /></label></div>
      <div className="admin-form-grid compact"><label>{kk ? 'Кімге' : 'Кому'}<select value={targetType} onChange={(e) => { setTargetType(e.target.value as typeof targetType); setTargets([]) }}><option value="user">{kk ? 'Таңдалған оқушылар' : 'Выбранные ученики'}</option><option value="grade">{kk ? 'Сынып' : 'Класс'}</option><option value="all">{kk ? 'Барлық оқушылар' : 'Все ученики'}</option></select></label><label>{kk ? 'Контент түрі' : 'Тип контента'}<select value={contentType} onChange={(e) => { setContentType(e.target.value as LearningContentType); setContentIds([]) }}><option value="section">{kk ? 'Бөлім' : 'Раздел'}</option><option value="topic">{kk ? 'Тақырып' : 'Тема'}</option><option value="level">{kk ? 'Квест / деңгей' : 'Квест / уровень'}</option><option value="boss">Boss Mission</option></select></label><label>{kk ? 'Қолжетімді' : 'Доступно с'}<input type="datetime-local" required value={availableFrom} onChange={(e) => setAvailableFrom(e.target.value)} /></label><label>{kk ? 'Мерзімі (міндетті емес)' : 'Срок (необязательно)'}<input type="datetime-local" min={availableFrom} value={dueAt} onChange={(e) => setDueAt(e.target.value)} /></label></div>
      <label className="admin-priority"><input type="checkbox" checked={priority === 'priority'} onChange={(e) => setPriority(e.target.checked ? 'priority' : 'normal')} />📌 {kk ? 'Басым тапсырма' : 'Приоритетное назначение'}</label>
      {targetType !== 'all' && <fieldset className="admin-choice-grid"><legend>{kk ? 'Алушылар' : 'Получатели'}</legend>{targetType === 'grade' ? ['5','6'].map((grade) => <label key={grade}><input type="checkbox" checked={targets.includes(grade)} onChange={() => toggle(grade, targets, setTargets)} />{grade}-{kk ? 'сынып' : 'й класс'}</label>) : students.map((student) => <label key={student.userId}><input type="checkbox" checked={targets.includes(student.userId)} onChange={() => toggle(student.userId, targets, setTargets)} /><AvatarImage value={student.avatar} label={student.nickname} /> {student.nickname} · {student.grade ?? '—'}</label>)}</fieldset>}
      <fieldset className="admin-choice-grid content"><legend>{kk ? 'Тапсырма элементтері' : 'Элементы назначения'}</legend>{catalog.map((item) => <label key={item.id}><input type="checkbox" checked={contentIds.includes(item.id)} onChange={() => toggle(item.id, contentIds, setContentIds)} /><span>{item.title}</span></label>)}</fieldset><button className="primary-button" type="submit">{kk ? 'Тағайындау' : 'Назначить'}</button></form>}
    <section className="admin-assignment-list">{rows.length === 0 ? <p className="admin-empty">{kk ? 'Әзірге тапсырма жоқ.' : 'Назначений пока нет.'}</p> : rows.map((item) => <article key={item.assignmentId} className={item.priority === 'priority' ? 'priority' : ''}><header><div><small>{item.priority === 'priority' ? '📌 PRIORITY' : item.status.toUpperCase()}</small><h2>{item.title[progress.language]}</h2><p>{item.description[progress.language]}</p></div><span>{item.dueAt ? new Intl.DateTimeFormat(kk ? 'kk-KZ' : 'ru-RU', { dateStyle: 'medium' }).format(new Date(item.dueAt)) : (kk ? 'Мерзімсіз' : 'Без срока')}</span></header><div className="assignment-analytics"><span><b>{item.assignedCount}</b>{kk ? 'Тағайындалды' : 'Назначено'}</span><span><b>{item.startedCount}</b>{kk ? 'Бастады' : 'Начали'}</span><span><b>{item.completedCount}</b>{kk ? 'Аяқтады' : 'Завершили'}</span><span><b>{item.averageScore}%</b>{kk ? 'Орташа нәтиже' : 'Средний результат'}</span><span><b>{item.averageAttempts}</b>{kk ? 'Орташа әрекет' : 'Среднее попыток'}</span></div><footer><small>{item.targetSummary} · {item.itemCount} {kk ? 'элемент' : 'элементов'}</small><div><button disabled={busy} onClick={() => void update(item, { priority: item.priority === 'priority' ? 'normal' : 'priority' })}>📌 {item.priority === 'priority' ? (kk ? 'Басымды алып тастау' : 'Снять приоритет') : (kk ? 'Басым ету' : 'Сделать приоритетным')}</button><button disabled={busy} onClick={() => void update(item, { status: item.status === 'active' ? 'archived' : 'active' })}>{item.status === 'active' ? (kk ? 'Мұрағаттау' : 'Архивировать') : (kk ? 'Қалпына келтіру' : 'Восстановить')}</button></div></footer></article>)}</section>
    {confirm && <AdminConfirmDialog title={kk ? 'Тапсырманы тағайындау керек пе?' : 'Создать назначение?'} confirmLabel={kk ? 'Тағайындау' : 'Назначить'} cancelLabel={kk ? 'Бас тарту' : 'Отмена'} busy={busy} onConfirm={() => void create()} onCancel={() => setConfirm(null)}><p>{kk ? `${confirm.targetValues.length} алушы тобына ${confirm.items.length} элемент тағайындалады.` : `${confirm.items.length} элементов будут назначены выбранной группе.`}</p></AdminConfirmDialog>}
  </>
}
