import { useEffect, useState } from 'react'
import { adminCopy } from '../content/admin'
import { fetchAdminAchievementAnalytics, fetchAdminDailyAnalytics, fetchAdminDashboard, fetchAdminWeakTopics } from '../services/adminService'
import { useGame } from '../store/GameStore'
import type { AdminAchievementAnalytics, AdminDailyAnalytics, AdminDashboardStats, AdminWeakTopic } from '../types/admin'
import { AdminError, AdminLoading } from './AdminDashboard'
import { levelTitle } from './AdminStudentDetail'
import { levelById } from '../content/levels'
import { sections } from '../content/sections'

export function AdminAnalytics({ mode='analytics' }: { mode?: 'analytics'|'results'|'sections' }) {
  const {progress}=useGame(); const copy=adminCopy(progress.language); const [daily,setDaily]=useState<AdminDailyAnalytics[]>([]); const [weak,setWeak]=useState<AdminWeakTopic[]>([]); const [dashboard,setDashboard]=useState<AdminDashboardStats|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(false)
  const [achievementAnalytics,setAchievementAnalytics]=useState<AdminAchievementAnalytics[]>([])
  const load=()=>{setLoading(true);setError(false);void Promise.all([fetchAdminDailyAnalytics(14),fetchAdminWeakTopics(20),fetchAdminDashboard(),fetchAdminAchievementAnalytics()]).then(([d,w,s,a])=>{setDaily(d);setWeak(w);setDashboard(s);setAchievementAnalytics(a)}).catch(()=>setError(true)).finally(()=>setLoading(false))}; useEffect(load,[])
  if(loading)return <AdminLoading/>; if(error)return <AdminError onRetry={load}/>
  const maxActive=Math.max(1,...daily.map(row=>row.activeStudents)); const sectionGroups=weak.reduce<Record<string,{errors:number;count:number}>>((acc,row)=>{const section=levelById[row.levelId]?.sectionId ?? row.levelId.split('-')[0];const target=acc[section]??{errors:0,count:0};target.errors+=row.errorRate;target.count+=1;acc[section]=target;return acc},{})
  const common=achievementAnalytics.slice(0,5);const rare=[...achievementAnalytics].sort((a,b)=>a.unlockPercent-b.unlockPercent).slice(0,5)
  return <><header className="admin-page-heading"><small>EDTECH ANALYTICS</small><h1>{mode==='results'?copy.results:mode==='sections'?copy.sections:copy.analytics}</h1></header>{mode==='analytics'&&dashboard&&<section className="admin-analytics-kpis"><article><small>{copy.xpEarned}</small><strong>{daily.reduce((sum,row)=>sum+row.xpEarned,0)}</strong></article><article><small>{copy.completedLevels}</small><strong>{daily.reduce((sum,row)=>sum+row.completedLevels,0)}</strong></article><article><small>{copy.averageAccuracy}</small><strong>{dashboard.averageAccuracy}%</strong></article><article><small>{copy.grade5} / {copy.grade6}</small><strong>{dashboard.grade5} / {dashboard.grade6}</strong></article></section>}{mode!=='results'&&<section className="admin-chart-card"><h2>{copy.activeStudents}</h2><div className="admin-bar-chart">{daily.map(row=><div key={row.day}><i style={{height:`${Math.max(4,row.activeStudents/maxActive*100)}%`}} title={`${row.activeStudents}`} /><small>{row.day.slice(5)}</small></div>)}</div></section>}{mode==='analytics'&&<section className="admin-achievement-analytics"><AchievementRates title={progress.language==='kk'?'Жиі алынатын жетістіктер':'Часто получаемые достижения'} rows={common} language={progress.language}/><AchievementRates title={progress.language==='kk'?'Сирек жетістіктер':'Редкие достижения'} rows={rare} language={progress.language}/></section>}{mode==='sections'?<section className="admin-weak-list">{Object.entries(sectionGroups).map(([sectionId,value],index)=>{const title=sections.find(section=>section.id===sectionId)?.title[progress.language]??sectionId;return <article key={sectionId}><b>{index+1}</b><strong>{title}</strong><span>{(value.errors/value.count).toFixed(1)}%</span></article>})}</section>:<section className="admin-weak-list"><h2>{copy.weak}</h2>{weak.length===0?<p>{copy.noData}</p>:weak.map((row,index)=><article key={row.levelId}><b>{index+1}</b><div><strong>{levelTitle(row.levelId,progress.language)}</strong><small>{row.attemptCount} {copy.attempts.toLowerCase()} · {row.completionCount} {copy.completedLevels.toLowerCase()} · {copy.averageAccuracy} {row.averageScore}%</small></div><span>{row.errorRate}%</span></article>)}</section>}</>
}

function AchievementRates({title,rows,language}:{title:string;rows:AdminAchievementAnalytics[];language:'kk'|'ru'}){return <article><h2>{title}</h2>{rows.map(row=><div key={row.code}><span><b>{row.title[language]}</b><small>{row.rarity} · {row.unlockedStudents}/{row.totalStudents}</small></span><strong>{row.unlockPercent}%</strong></div>)}</article>}
