import { useEffect, useState } from 'react'
import { achievements } from '../content/achievements'
import { sections } from '../content/sections'
import { topics } from '../content/topics'
import { fetchAdminStudents } from '../services/adminService'
import { fetchAdminStudentAccess, fetchAdminStudentAssignments } from '../services/learningService'
import { useGame } from '../store/GameStore'
import type { AdminStudent } from '../types/admin'
import type { LearningAccess, StudentAssignment } from '../types/learning'
import { AvatarImage } from '../components/AvatarImage'

type PreviewView = 'guest'|'home'|'map'|'profile'|'achievements'|'leaderboard'|'topic'|'quest'

export function AdminSitePreview() {
  const { progress } = useGame(); const kk = progress.language === 'kk'; const [view, setView] = useState<PreviewView>('home'); const [students, setStudents] = useState<AdminStudent[]>([]); const [studentId, setStudentId] = useState(''); const [access, setAccess] = useState<LearningAccess[]>([]); const [assignments, setAssignments] = useState<StudentAssignment[]>([])
  useEffect(() => { void fetchAdminStudents({ search: '', grade: null, active: 'all', sort: 'nickname', page: 0 }).then(setStudents).catch(() => undefined) }, [])
  useEffect(() => { if (!studentId) { setAccess([]); setAssignments([]); return } void Promise.all([fetchAdminStudentAccess(studentId), fetchAdminStudentAssignments(studentId)]).then(([a, x]) => { setAccess(a); setAssignments(x) }).catch(() => undefined) }, [studentId])
  const state = (type: LearningAccess['contentType'], id: string) => access.find((item) => item.contentType === type && item.contentId === id)?.accessState
  return <><header className="admin-page-heading"><small>READ-ONLY</small><h1>{kk ? 'Сайтты алдын ала қарау' : 'Предпросмотр сайта'}</h1></header><section className="preview-toolbar"><span>🛡 ADMIN PREVIEW · {kk ? 'ТЕК ҚАРАУ' : 'ТОЛЬКО ЧТЕНИЕ'}</span><select value={view} onChange={(e) => setView(e.target.value as PreviewView)}>{(['guest','home','map','profile','achievements','leaderboard','topic','quest'] as PreviewView[]).map((item) => <option key={item} value={item}>{previewLabel(item, kk)}</option>)}</select><select value={studentId} onChange={(e) => setStudentId(e.target.value)}><option value="">{kk ? 'Тестілік деректер' : 'Тестовые данные'}</option>{students.map((student) => <option key={student.userId} value={student.userId}>{student.nickname}</option>)}</select></section><section className="site-preview-frame"><div className="preview-ribbon">ADMIN PREVIEW · NO XP · NO SUBMISSIONS</div><header><strong>SCIENCE QUEST <em>KZ</em></strong><span>ҚАЗ | РУС</span></header>{view === 'guest' && <PreviewGuest kk={kk} />}{view === 'home' && <PreviewHome kk={kk} assignments={assignments} />}{view === 'map' && <PreviewMap kk={kk} state={state} />}{view === 'profile' && <PreviewProfile kk={kk} student={students.find((item) => item.userId === studentId)} />}{view === 'achievements' && <div className="preview-grid"><h2>{kk ? 'Жетістіктер' : 'Достижения'}</h2>{achievements.slice(0, 6).map((item) => <article key={item.id}><span>{item.icon}</span><strong>{item.title[progress.language]}</strong></article>)}</div>}{view === 'leaderboard' && <div className="preview-ranking"><h2>{kk ? 'Рейтинг' : 'Рейтинг'}</h2>{students.slice(0, 5).map((student, index) => <article key={student.userId}><b>#{index + 1}</b><AvatarImage value={student.avatar} label={student.nickname} /><strong>{student.nickname}</strong><em>{student.xp} XP</em></article>)}</div>}{view === 'topic' && <PreviewTopic kk={kk} />}{view === 'quest' && <PreviewQuest kk={kk} />}</section><p className="admin-safe-note">🔒 {kk ? 'Preview әрекеттері серверлік RPC шақырмайды және оқушы атынан әрекет етпейді.' : 'Preview не вызывает игровые RPC и не действует от имени ученика.'}</p></>
}

function PreviewGuest({ kk }: { kk: boolean }) { return <div className="preview-hero"><small>ҒЫЛЫМ • НАУКА</small><h2>SCIENCE QUEST <em>KZ</em></h2><p>{kk ? 'Жаратылыстану әлеміне саяхат' : 'Путешествие в мир естествознания'}</p><button disabled>{kk ? 'Тіркелу' : 'Регистрация'}</button></div> }
function PreviewHome({ kk, assignments }: { kk: boolean; assignments: StudentAssignment[] }) { return <div className="preview-home"><h2>{kk ? 'Қайырлы күн, зерттеуші!' : 'Добрый день, исследователь!'}</h2><article><span>📌</span><div><small>{kk ? 'МҰҒАЛІМ ТАПСЫРМАСЫ' : 'ЗАДАНИЕ ПРЕПОДАВАТЕЛЯ'}</small><strong>{assignments[0]?.title[kk ? 'kk' : 'ru'] ?? (kk ? 'Фотосинтезді қайталау' : 'Повторить фотосинтез')}</strong></div><b>{assignments[0]?.progressPercent ?? 40}%</b></article></div> }
function PreviewMap({ kk, state }: { kk: boolean; state: (type: LearningAccess['contentType'], id: string) => string | undefined }) { return <div className="preview-map"><h2>{kk ? 'Ғылым картасы' : 'Карта науки'}</h2>{sections.map((section) => <section key={section.id}><h3>{section.icon} {section.title[kk ? 'kk' : 'ru']}</h3><div>{topics.filter((topic) => topic.sectionId === section.id).map((topic) => { const value = state('topic', topic.id); if (value === 'hidden') return null; return <article key={topic.id}><span>{value === 'completed' ? '✅' : value === 'assigned' ? '📌' : value === 'locked' ? '🔒' : '✨'}</span><strong>{topic.title[kk ? 'kk' : 'ru']}</strong></article> })}</div></section>)}</div> }
function PreviewProfile({ kk, student }: { kk: boolean; student?: AdminStudent }) { return <div className="preview-profile"><AvatarImage value={student?.avatar ?? '🧑‍🔬'} label={student?.nickname ?? 'ScienceAyan'} /><h2>{student?.nickname ?? 'ScienceAyan'}</h2><p>{student?.grade ?? 5}-{kk ? 'сынып' : 'й класс'} · {student?.xp ?? 1240} XP</p></div> }
function PreviewTopic({ kk }: { kk: boolean }) { const topic = topics[14]; return <div className="preview-topic"><span>{topic.icon}</span><small>{kk ? 'ТІРІ ТАБИҒАТ' : 'ЖИВАЯ ПРИРОДА'}</small><h2>{topic.title[kk ? 'kk' : 'ru']}</h2><p>{topic.theory[kk ? 'kk' : 'ru']}</p></div> }
function PreviewQuest({ kk }: { kk: boolean }) { return <div className="preview-quest"><span>🧪</span><small>LEVEL 3 · EXPERIMENT</small><h2>{kk ? 'Виртуалды тәжірибе' : 'Виртуальный эксперимент'}</h2><p>{kk ? 'Параметрлерді өзгертіп, нәтижені талда.' : 'Измени параметры и проанализируй результат.'}</p><button disabled>{kk ? 'Тексеру' : 'Проверить'}</button></div> }
const previewLabel = (view: PreviewView, kk: boolean) => ({ guest: kk ? 'Қонақ' : 'Guest View', home: kk ? 'Оқушының басты беті' : 'Student Home', map: kk ? 'Ойын картасы' : 'Game Map', profile: kk ? 'Профиль' : 'Профиль', achievements: kk ? 'Жетістіктер' : 'Достижения', leaderboard: kk ? 'Рейтинг' : 'Рейтинг', topic: kk ? 'Тақырып' : 'Тема', quest: kk ? 'Квест' : 'Квест' }[view])
